import fs from 'fs';

const urls = {
  regular: 'https://fonts.gstatic.com/s/plusjakartasans/v12/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_qU7NSg.ttf',
  bold: 'https://fonts.gstatic.com/s/plusjakartasans/v12/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNSg.ttf',
};

async function download(url) {
  const resp = await fetch(url);
  if (!resp.ok) throw new Error(`Failed to download: ${resp.status}`);
  return Buffer.from(await resp.arrayBuffer());
}

const [regularBuf, boldBuf] = await Promise.all([
  download(urls.regular),
  download(urls.bold),
]);

const regularB64 = regularBuf.toString('base64');
const boldB64 = boldBuf.toString('base64');

const tsContent = `// Auto-generated by scripts/generate-font-ts.mjs
// Plus Jakarta Sans TTF fonts as base64

export const PLUS_JAKARTA_SANS_REGULAR = '${regularB64}';
export const PLUS_JAKARTA_SANS_BOLD = '${boldB64}';
`;

const outPath = '/Users/Staberman/Desktop/PresupuestadoPro/lib/plus-jakarta-sans.ts';
fs.writeFileSync(outPath, tsContent);
console.log(`Font TS generated: ${outPath}`);
console.log(`Regular: ${(regularBuf.length / 1024).toFixed(0)}KB`);
console.log(`Bold: ${(boldBuf.length / 1024).toFixed(0)}KB`);
